version: '3.4'

services:
  db:
    image: 'postgres'
    environment:
      - POSTGRES_PASSWORD=secret
    ports:
      - 5432:5432
  api:
    build: .
    ports:
      - 5000:5000
    links: 
      - db