# version: '3.4'

# services:
#   api:
#     environment:
#       - ASPNETCORE_ENVIRONMENT=Development
#       - ASPNETCORE_URLS=https://+:443;http://+:80
#     ports:
#       - "80"
#       - "443"
#     volumes:
#       - ${APPDATA}/Microsoft/UserSecrets:C:\Users\ContainerUser\AppData\Roaming\Microsoft\UserSecrets:ro
#       - ${APPDATA}/ASP.NET/Https:C:\Users\ContainerUser\AppData\Roaming\ASP.NET\Https:ro

version: '3.4'

services:
  db:
    image: 'postgres'
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=postgres
      - POSTGRES_DB=it_mentor_db
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data